[package]
name = "cosmogony"
version = "0.2.0"
authors = ["Adrien Matissart <a.matissart@qwantresearch.com>"]
build = "build.rs"

[dependencies]
log = "0.4"
env_logger = "0.5"
geo = "0.6"
structopt = "0.1"
structopt-derive = "0.1"
osmpbfreader = "*"
serde = {version = "1", features = ["rc"]}
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
itertools = "*"
geojson = "0.9"
failure = "0.1"
failure_derive = "0.1"
gst = "0.1.3"
ordered-float = "0.0.2"
osm_boundaries_utils = "0.2"
geos = { git = "https://github.com/QwantResearch/rust-geos.git"}
