[package]
name = "cosmogony"
version = "0.1.0"
authors = ["Adrien Matissart <a.matissart@qwantresearch.com>"]
build = "build.rs"

[dependencies]
log = "0.4"
geo = "0.4"
mimir = { git = "https://github.com/antoine-de/mimirsbrunn.git", branch = "fix_lat_lon" }
mimirsbrunn = { git = "https://github.com/antoine-de/mimirsbrunn.git", branch = "fix_lat_lon" }
structopt = "0.1"
structopt-derive = "0.1"
osmpbfreader = "*"
serde = {version = "1", features = ["rc"]}
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
itertools = "*"
geojson = "0.8"
failure = "0.1"
failure_derive = "0.1"
gst = "0.1.3"
ordered-float = "0.0.2"
geos = { git = "https://github.com/amatissart/rust-geos.git" }