[package]
name = "cosmogony"
version = "0.4.0"
authors = ["Adrien Matissart <a.matissart@qwantresearch.com>", "Antoine Desbordes <antoine.desbordes@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/osm-without-borders/cosmogony"
homepage = "http://cosmogony.world"
keywords = ["osm", "boundary", "geography"]
categories = ["science", "algorithms"]
description = "Provides geographical zones with a structured hierarchy"
readme = "README.md"


[badges]
travis-ci = { repository = "osm-without-borders/cosmogony" }

[dependencies]
log = "0.4"
env_logger = "0.5"
geo = "0.10.2"
geo-types = "0.2.0"
structopt = "0.1"
structopt-derive = "0.1"
osmpbfreader = "^0.11"
serde = {version = "1", features = ["rc"]}
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
itertools = "0.7"
geojson = "0.12.0"
failure = "0.1"
failure_derive = "0.1"
gst = "0.1.3"
ordered-float = "0.0.2"
osm_boundaries_utils = { version="0.3", git = "https://github.com/QwantResearch/osm_boundaries_utils_rs.git", rev = "86374bbfc75798dd836c85214f72b35562bae23a" }
geos = { version="3.0", git = "https://github.com/antoine-de/rust-geos.git", rev = "09aeb1aff841b9a321fa8c205234d03ea8f73cba" }
regex = "0.2"
lazy_static = "1.0.0"
flate2 = "1.0"
rayon = "1.0.1"

[dev-dependencies]
approx = "0.2.0"
