[package]
name = "cosmogony"
version = "0.5.0"
authors = ["Adrien Matissart <a.matissart@qwantresearch.com>", "Antoine Desbordes <antoine.desbordes@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/osm-without-borders/cosmogony"
homepage = "http://cosmogony.world"
keywords = ["osm", "boundary", "geography"]
categories = ["science", "algorithms"]
description = "Provides geographical zones with a structured hierarchy"
readme = "README.md"
edition = "2018"


[badges]
travis-ci = { repository = "osm-without-borders/cosmogony" }

[dependencies]
log = "0.4"
env_logger = "0.5"
geo = "0.10.2"
geo-types = "0.2.0"
structopt = "0.2"
osmpbfreader = "^0.11"
serde = {version = "1", features = ["rc"]}
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
itertools = "0.7"
geojson = "0.12.0"
failure = "0.1"
failure_derive = "0.1"
gst = "0.1.3"
ordered-float = "0.0.2"
osm_boundaries_utils = "0.3"
geos = "3.0"
regex = "0.2"
lazy_static = "1.0.0"
flate2 = "1.0"
rayon = "1.0.1"
include_dir = "0.2"
snap = "0.2"

[dev-dependencies]
approx = "0.2.0"
